//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaccaMyPageScraper.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaccaMyPageScraper.Localization.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieve Icon.
        /// </summary>
        public static string AchieveIcon {
            get {
                return ResourceManager.GetString("AchieveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aime ID.
        /// </summary>
        public static string AimeId {
            get {
                return ResourceManager.GetString("AimeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime/Pop.
        /// </summary>
        public static string Genre_AnimePop {
            get {
                return ResourceManager.GetString("Genre_AnimePop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string Genre_Original {
            get {
                return ResourceManager.GetString("Genre_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARDCORE TANO*C.
        /// </summary>
        public static string Genre_TanoC {
            get {
                return ResourceManager.GetString("Genre_TanoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touhou.
        /// </summary>
        public static string Genre_Touhou {
            get {
                return ResourceManager.GetString("Genre_Touhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5 Dimension.
        /// </summary>
        public static string Genre_TwoPointFive {
            get {
                return ResourceManager.GetString("Genre_TwoPointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety.
        /// </summary>
        public static string Genre_Variety {
            get {
                return ResourceManager.GetString("Genre_Variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocaloid.
        /// </summary>
        public static string Genre_Vocaloid {
            get {
                return ResourceManager.GetString("Genre_Vocaloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Jacket Image.
        /// </summary>
        public static string MusicImage {
            get {
                return ResourceManager.GetString("MusicImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Metadata.
        /// </summary>
        public static string MusicMetadata {
            get {
                return ResourceManager.GetString("MusicMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Ranking.
        /// </summary>
        public static string MusicRanking {
            get {
                return ResourceManager.GetString("MusicRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Count.
        /// </summary>
        public static string PlayCount {
            get {
                return ResourceManager.GetString("PlayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Count (co-op).
        /// </summary>
        public static string PlayCountCoop {
            get {
                return ResourceManager.GetString("PlayCountCoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Count (vs).
        /// </summary>
        public static string PlayCountVersus {
            get {
                return ResourceManager.GetString("PlayCountVersus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Icon.
        /// </summary>
        public static string PlayerIcon {
            get {
                return ResourceManager.GetString("PlayerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Rate.
        /// </summary>
        public static string PlayerRate {
            get {
                return ResourceManager.GetString("PlayerRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Icon.
        /// </summary>
        public static string RateIcon {
            get {
                return ResourceManager.GetString("RateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Icon.
        /// </summary>
        public static string StageIcon {
            get {
                return ResourceManager.GetString("StageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Metadata.
        /// </summary>
        public static string StageMetadata {
            get {
                return ResourceManager.GetString("StageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Ranking.
        /// </summary>
        public static string StageRanking {
            get {
                return ResourceManager.GetString("StageRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP Earned.
        /// </summary>
        public static string TotalRpEarned {
            get {
                return ResourceManager.GetString("TotalRpEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total RP Ranking.
        /// </summary>
        public static string TotalRpRanking {
            get {
                return ResourceManager.GetString("TotalRpRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RP Spent.
        /// </summary>
        public static string TotalRpSpent {
            get {
                return ResourceManager.GetString("TotalRpSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score Ranking.
        /// </summary>
        public static string TotalScoreRanking {
            get {
                return ResourceManager.GetString("TotalScoreRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy.
        /// </summary>
        public static string Trophy {
            get {
                return ResourceManager.GetString("Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy Icon.
        /// </summary>
        public static string TrophyIcon {
            get {
                return ResourceManager.GetString("TrophyIcon", resourceCulture);
            }
        }
    }
}
