//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaccaMyPageScraper.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaccaMyPageScraper.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AchieveAllMarvelous {
            get {
                object obj = ResourceManager.GetObject("AchieveAllMarvelous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AchieveClear {
            get {
                object obj = ResourceManager.GetObject("AchieveClear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AchieveFullCombo {
            get {
                object obj = ResourceManager.GetObject("AchieveFullCombo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AchieveMissless {
            get {
                object obj = ResourceManager.GetObject("AchieveMissless", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AchieveNo {
            get {
                object obj = ResourceManager.GetObject("AchieveNo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateA {
            get {
                object obj = ResourceManager.GetObject("RateA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateAA {
            get {
                object obj = ResourceManager.GetObject("RateAA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateAAA {
            get {
                object obj = ResourceManager.GetObject("RateAAA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateB {
            get {
                object obj = ResourceManager.GetObject("RateB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateC {
            get {
                object obj = ResourceManager.GetObject("RateC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateD {
            get {
                object obj = ResourceManager.GetObject("RateD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateMaster {
            get {
                object obj = ResourceManager.GetObject("RateMaster", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateNo {
            get {
                object obj = ResourceManager.GetObject("RateNo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateS {
            get {
                object obj = ResourceManager.GetObject("RateS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateS_Plus {
            get {
                object obj = ResourceManager.GetObject("RateS_Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateSS {
            get {
                object obj = ResourceManager.GetObject("RateSS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateSS_Plus {
            get {
                object obj = ResourceManager.GetObject("RateSS_Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateSSS {
            get {
                object obj = ResourceManager.GetObject("RateSSS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RateSSS_Plus {
            get {
                object obj = ResourceManager.GetObject("RateSSS_Plus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageI_Blue {
            get {
                object obj = ResourceManager.GetObject("StageI_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageI_Gold {
            get {
                object obj = ResourceManager.GetObject("StageI_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageI_Silver {
            get {
                object obj = ResourceManager.GetObject("StageI_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageII_Blue {
            get {
                object obj = ResourceManager.GetObject("StageII_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageII_Gold {
            get {
                object obj = ResourceManager.GetObject("StageII_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageII_Silver {
            get {
                object obj = ResourceManager.GetObject("StageII_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIII_Blue {
            get {
                object obj = ResourceManager.GetObject("StageIII_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIII_Gold {
            get {
                object obj = ResourceManager.GetObject("StageIII_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIII_Silver {
            get {
                object obj = ResourceManager.GetObject("StageIII_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIV_Blue {
            get {
                object obj = ResourceManager.GetObject("StageIV_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIV_Gold {
            get {
                object obj = ResourceManager.GetObject("StageIV_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIV_Silver {
            get {
                object obj = ResourceManager.GetObject("StageIV_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIX_Blue {
            get {
                object obj = ResourceManager.GetObject("StageIX_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIX_Gold {
            get {
                object obj = ResourceManager.GetObject("StageIX_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageIX_Silver {
            get {
                object obj = ResourceManager.GetObject("StageIX_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageNone {
            get {
                object obj = ResourceManager.GetObject("StageNone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;1&quot;:{&quot;tracks&quot;:[{&quot;id&quot;:2058,&quot;title&quot;:&quot;sister&apos;s noise&quot;,&quot;level&quot;:&quot;2&quot;,&quot;difficulty&quot;:&quot;Normal&quot;},{&quot;id&quot;:2214,&quot;title&quot;:&quot;バレリーコ&quot;,&quot;level&quot;:&quot;3&quot;,&quot;difficulty&quot;:&quot;Normal&quot;},{&quot;id&quot;:2206,&quot;title&quot;:&quot;Scream out!&quot;,&quot;level&quot;:&quot;4&quot;,&quot;difficulty&quot;:&quot;Normal&quot;}],&quot;clearCondition&quot;:{&quot;judge&quot;:&quot;Miss&quot;,&quot;count&quot;:50},&quot;lifeRestore&quot;:20},&quot;2&quot;:{&quot;tracks&quot;:[{&quot;id&quot;:2207,&quot;title&quot;:&quot;MAGENTA POTION&quot;,&quot;level&quot;:&quot;4&quot;,&quot;difficulty&quot;:&quot;Normal&quot;},{&quot;id&quot;:2209,&quot;title&quot;:&quot;ATAMA WARUI&quot;,&quot;level&quot;:&quot;5&quot;,&quot;difficulty&quot;:&quot;Normal&quot;},{&quot;id&quot;:2229,&quot;title&quot;:&quot;Night Club Junkie&quot;,&quot;level&quot;:&quot;6+&quot;,&quot;difficulty&quot;:&quot;Hard&quot;....
        /// </summary>
        internal static string StageUpJson {
            get {
                return ResourceManager.GetString("StageUpJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageV_Blue {
            get {
                object obj = ResourceManager.GetObject("StageV_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageV_Gold {
            get {
                object obj = ResourceManager.GetObject("StageV_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageV_Silver {
            get {
                object obj = ResourceManager.GetObject("StageV_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVI_Blue {
            get {
                object obj = ResourceManager.GetObject("StageVI_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVI_Gold {
            get {
                object obj = ResourceManager.GetObject("StageVI_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVI_Silver {
            get {
                object obj = ResourceManager.GetObject("StageVI_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVII_Blue {
            get {
                object obj = ResourceManager.GetObject("StageVII_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVII_Gold {
            get {
                object obj = ResourceManager.GetObject("StageVII_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVII_Silver {
            get {
                object obj = ResourceManager.GetObject("StageVII_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVIII_Blue {
            get {
                object obj = ResourceManager.GetObject("StageVIII_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVIII_Gold {
            get {
                object obj = ResourceManager.GetObject("StageVIII_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageVIII_Silver {
            get {
                object obj = ResourceManager.GetObject("StageVIII_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageX_Blue {
            get {
                object obj = ResourceManager.GetObject("StageX_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageX_Gold {
            get {
                object obj = ResourceManager.GetObject("StageX_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageX_Silver {
            get {
                object obj = ResourceManager.GetObject("StageX_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXI_Blue {
            get {
                object obj = ResourceManager.GetObject("StageXI_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXI_Gold {
            get {
                object obj = ResourceManager.GetObject("StageXI_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXI_Silver {
            get {
                object obj = ResourceManager.GetObject("StageXI_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXII_Blue {
            get {
                object obj = ResourceManager.GetObject("StageXII_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXII_Gold {
            get {
                object obj = ResourceManager.GetObject("StageXII_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXII_Silver {
            get {
                object obj = ResourceManager.GetObject("StageXII_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXIII_Blue {
            get {
                object obj = ResourceManager.GetObject("StageXIII_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXIII_Gold {
            get {
                object obj = ResourceManager.GetObject("StageXIII_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXIII_Silver {
            get {
                object obj = ResourceManager.GetObject("StageXIII_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXIV_Blue {
            get {
                object obj = ResourceManager.GetObject("StageXIV_Blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXIV_Gold {
            get {
                object obj = ResourceManager.GetObject("StageXIV_Gold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StageXIV_Silver {
            get {
                object obj = ResourceManager.GetObject("StageXIV_Silver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_1_1 {
            get {
                object obj = ResourceManager.GetObject("Trophy_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_1_2 {
            get {
                object obj = ResourceManager.GetObject("Trophy_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_1_3 {
            get {
                object obj = ResourceManager.GetObject("Trophy_1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_1_4 {
            get {
                object obj = ResourceManager.GetObject("Trophy_1_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_2_1 {
            get {
                object obj = ResourceManager.GetObject("Trophy_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_2_2 {
            get {
                object obj = ResourceManager.GetObject("Trophy_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_2_3 {
            get {
                object obj = ResourceManager.GetObject("Trophy_2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_2_4 {
            get {
                object obj = ResourceManager.GetObject("Trophy_2_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_3_1 {
            get {
                object obj = ResourceManager.GetObject("Trophy_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_3_2 {
            get {
                object obj = ResourceManager.GetObject("Trophy_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_3_3 {
            get {
                object obj = ResourceManager.GetObject("Trophy_3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_3_4 {
            get {
                object obj = ResourceManager.GetObject("Trophy_3_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_4_1 {
            get {
                object obj = ResourceManager.GetObject("Trophy_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_4_2 {
            get {
                object obj = ResourceManager.GetObject("Trophy_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_4_3 {
            get {
                object obj = ResourceManager.GetObject("Trophy_4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_4_4 {
            get {
                object obj = ResourceManager.GetObject("Trophy_4_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_5_1 {
            get {
                object obj = ResourceManager.GetObject("Trophy_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_5_2 {
            get {
                object obj = ResourceManager.GetObject("Trophy_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_5_3 {
            get {
                object obj = ResourceManager.GetObject("Trophy_5_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_5_4 {
            get {
                object obj = ResourceManager.GetObject("Trophy_5_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_6_1 {
            get {
                object obj = ResourceManager.GetObject("Trophy_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_6_2 {
            get {
                object obj = ResourceManager.GetObject("Trophy_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_6_3 {
            get {
                object obj = ResourceManager.GetObject("Trophy_6_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trophy_6_4 {
            get {
                object obj = ResourceManager.GetObject("Trophy_6_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TrophyBronze {
            get {
                object obj = ResourceManager.GetObject("TrophyBronze", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TrophyGold {
            get {
                object obj = ResourceManager.GetObject("TrophyGold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TrophyPlatinum {
            get {
                object obj = ResourceManager.GetObject("TrophyPlatinum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TrophySilver {
            get {
                object obj = ResourceManager.GetObject("TrophySilver", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
