//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaccaMyPageScraper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataFilePath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFilePath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaccaMyPageScraper.Resources.DataFilePath", typeof(DataFilePath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/aime_id.txt.
        /// </summary>
        public static string AimeId {
            get {
                return ResourceManager.GetString("AimeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/player/.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/player/player.csv.
        /// </summary>
        public static string PlayerData {
            get {
                return ResourceManager.GetString("PlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/player/image/player_icon.png.
        /// </summary>
        public static string PlayerIcon {
            get {
                return ResourceManager.GetString("PlayerIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/player/image/.
        /// </summary>
        public static string PlayerImage {
            get {
                return ResourceManager.GetString("PlayerImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/player/image/player_stage.png.
        /// </summary>
        public static string PlayerStageIcon {
            get {
                return ResourceManager.GetString("PlayerStageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/records/.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/records/records.csv.
        /// </summary>
        public static string RecordData {
            get {
                return ResourceManager.GetString("RecordData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data/.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
    }
}
